name: CICD
on:
  push:
   branches:
    - "*"
  pull_request: 
    branches: 
    - "*"

jobs: 
  # The “build” workflow 
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with: 
        go-version: '1.14.0'
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
    - name: Run build
      run: go build .
    - name: Run vet & lint
      run: |
        go vet .
        golint .
    - name: Run testing
      run: go test -v
    - name: Run program
      run: GODEBUG=gctrace=1 go run start.go
    - name: notification
      uses: xinthink/action-telegram@v1.1
      with:
        botToken: ${{ secrets.BOTTOKEN }}
        chatId: ${{ secrets.CHATID }}
        jobStatus: ${{ job.status }}
